id = "cangjie"
name = "Cangjie"
version = "1.0.5"
schema_version = 1
description = "Cangjie language support for Zed"
authors = ["Goway_Hui <19168370426@163.com>"]
repository = "https://gitcode.com/Goway_Hui/CangjieTreeSitter.git"

[grammars.cangjie]
repository = "https://gitcode.com/Goway_Hui/CangjieTreeSitter.git"
rev = "e4661888ad35c6fa439448f6c30dac8def950aec"

[language_servers.cangjie-lsp]
name = "Cangjie LSP"
languages = ["Cangjie"]
